export const initialThemes = [
  {
    name: "Programming",
    nameId: "programming",
    tags: [
      "javascript",
      "python",
      "typescript",
      "nodejs",
      "software development",
      "software engineering",
      "c++",
      "c#",
      "java",
      "php",
      "go",
      "rust",
      "kotlin",
      "swift",
      "ruby",
      "dart",
      "web development",
      "data science",
      "mobile development",
      "game development",
      "systems programming",
    ],
  },
  {
    name: "Frameworks & Libraries",
    nameId: "frameworks_&libraries",
    tags: [
      "react",
      "vue",
      "angular",
      "frontend",
      "backend",
      "fullstack",
      "django",
      "express.js",
      "spring",
      "flask",
      "next.js",
      "nuxt.js",
      "svelte",
      "jquery",
      "bootstrap",
      "tailwind css",
      "material-ui",
    ],
  },
  {
    name: "Cloud & Infrastructure",
    nameId: "cloud&infrastructure",
    tags: [
      "docker",
      "kubernetes",
      "aws",
      "azure",
      "gcp",
      "cloud",
      "cloud computing",
      "cloud native",
      "cloud infrastructure",
      "cloud services",
      "serverless",
      "multi-cloud",
      "hybrid cloud",
      "edge computing",
      "virtualization",
      "containerization",
      "iam",
      "compute",
      "storage",
      "networking",
    ],
  },
  {
    name: "DevOps",
    nameId: "devops",
    tags: [
      "devops",
      "git",
      "ci/cd",
      "testing",
      "cloud operations",
      "cloud security",
      "cloud deployment",
      "cloud monitoring",
      "cloud logging",
      "cloud automation",
      "jenkins",
      "gitlab ci",
      "github actions",
      "terraform",
      "ansible",
      "chef",
      "puppet",
      "infrastructure as code",
    ],
  },
  {
    name: "Databases",
    nameId: "databases",
    tags: [
      "database",
      "sql",
      "nosql",
      "mongodb",
      "postgresql",
      "redis",
      "mysql",
      "sqlite",
      "mariadb",
      "oracle",
      "elasticsearch",
      "firebase",
      "dynamodb",
      "data warehousing",
      "data modeling",
    ],
  },
  {
    name: "AI & Machine Learning",
    nameId: "ai&machine_learning",
    tags: [
      "machine learning",
      "ai",
      "deep learning",
      "neural network",
      "supervised learning",
      "unsupervised learning",
      "reinforcement learning",
      "natural language processing",
      "nlp",
      "computer vision",
      "data science",
      "data analysis",
      "predictive modeling",
      "generative ai",
    ],
  },
  {
    name: "Mobile",
    nameId: "mobile",
    tags: [
      "mobile",
      "ios",
      "android",
      "swift",
      "kotlin",
      "react native",
      "flutter",
      "cross-platform",
      "native development",
      "app store optimization",
      "monetization",
    ],
  },
  {
    name: "Architecture & Design",
    nameId: "architecture&_design",
    tags: [
      "api",
      "microservices",
      "serverless",
      "software architecture",
      "software design",
      "cloud architecture",
      "cloud design",
      "cloud engineering",
      "event-driven architecture",
      "monolith",
      "layered architecture",
      "design patterns",
      "scalability",
      "security",
      "resilience",
    ],
  },
  {
    name: "Business",
    nameId: "business",
    tags: [
      "entrepreneurship",
      "startups",
      "marketing",
      "finance",
      "management",
      "leadership",
      "sales",
      "strategy",
      "investing",
      "e-commerce",
      "market research",
      "business plan",
      "financial analysis",
      "supply chain",
      "operations",
      "branding",
      "small business",
      "corporate culture",
      "b2b",
      "b2c",
      "cash flow",
      "profit margin",
      "networking",
      "roi",
    ],
  },
  {
    name: "Art",
    nameId: "art",
    tags: [
      "painting",
      "sculpture",
      "drawing",
      "digital art",
      "art history",
      "contemporary art",
      "modern art",
      "abstract art",
      "pop art",
      "street art",
      "illustration",
      "ceramics",
      "photography",
      "mixed media",
      "art criticism",
      "acrylic painting",
      "watercolor",
      "oil painting",
      "sketching",
      "printmaking",
      "art gallery",
    ],
  },
  {
    name: "Books",
    nameId: "books",
    tags: [
      "fiction",
      "non-fiction",
      "novel",
      "fantasy",
      "science fiction",
      "thriller",
      "mystery",
      "biography",
      "memoir",
      "poetry",
      "young adult",
      "children's literature",
      "book review",
      "literary analysis",
      "reading",
      "writing",
      "dystopian",
      "historical fiction",
      "literary fiction",
      "mythology",
      "horror",
    ],
  },
  {
    name: "Cinema",
    nameId: "cinema",
    tags: [
      "film",
      "movie review",
      "director",
      "screenwriting",
      "film production",
      "cinematography",
      "documentary",
      "indie film",
      "hollywood",
      "foreign film",
      "action",
      "comedy",
      "drama",
      "horror",
      "science fiction",
      "western",
      "animation",
      "crime",
      "historical film",
      "editing",
      "post-production",
      "pre-production",
      "special effects",
    ],
  },
  {
    name: "Photography",
    nameId: "photography",
    tags: [
      "landscape photography",
      "portrait photography",
      "street photography",
      "photojournalism",
      "camera",
      "lens",
      "editing",
      "lighting",
      "composition",
      "black and white",
      "photography tips",
      "photo editing",
      "darkroom",
      "aperture",
      "shutter speed",
      "iso",
      "focal length",
      "depth of field",
      "dslr",
      "mirrorless",
    ],
  },
  {
    name: "Animals",
    nameId: "animals",
    tags: [
      "wildlife",
      "pets",
      "cats",
      "dogs",
      "birds",
      "marine life",
      "conservation",
      "zoology",
      "animal behavior",
      "animal rescue",
      "veterinary medicine",
      "endangered species",
      "animal kingdom",
      "exotic animals",
      "animal husbandry",
      "ecosystem",
      "biodiversity",
      "zoos",
      "extinct species",
    ],
  },
  {
    name: "Science",
    nameId: "science",
    tags: [
      "astronomy",
      "biology",
      "chemistry",
      "physics",
      "geology",
      "space exploration",
      "scientific research",
      "scientific method",
      "biotechnology",
      "genetics",
      "neuroscience",
      "robotics",
      "sustainability",
      "climate change",
      "earth science",
      "scientific discoveries",
      "quantum physics",
      "evolution",
      "ecology",
      "genomics",
      "epigenetics",
      "geography",
      "astrophysics",
    ],
  },
];
